kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: bctw-cronjob-ats
  namespace: 0dff19-prod
  labels:
    cronjob: bctw-cronjob-ats
    template: bctw-cronjob-ats
spec:
  schedule: '0 * * * *'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: bctw-cronjob-ats
              image: >-
                image-registry.openshift-image-registry.svc:5000/0dff19-tools/bctw-data-collector:dev
              command:
                - npm
                - run
                - ats
              env:
                - name: NODE_ENV
                  value: production
                - name: POSTGRES_SERVER_HOST
                  value: bctw-db
                - name: POSTGRES_SERVER_PORT
                  value: '5432'
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: bctw
                      key: username
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bctw
                      key: password
                - name: POSTGRES_DB
                  value: bctw
                - name: VENDOR_API_CREDENTIALS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: vendor-api-credentials-pkey
                      key: key
                - name: ATS_API_CREDENTIAL_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ats-account-identifier-1
                      key: name
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3